theme: jekyll-theme-leap-day

# Site wide configuration
title: Transportation Data Science
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Brandon
  avatar: 
  bio: "This is a sample Jekyll academic website."
  email: 
  # Do not include the @ symbol in your Twitter username
  twitter: 
  linkedin: #username
  github: brandonw824
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
